name: Build Now

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter Tag: (e.g. v0.0.1)'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: ./build.ps1

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: ~build/deploy/*.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        tag_name: ${{ inputs.tag }}
        files: ~build/deploy/*.zip
        release_name: FakePDB_bin
        draft: false
        generate_release_notes: true
        prerelease: false
